cities:
  - name: san_francisco
    base_url: http://data.insideairbnb.com/united-states/ca/san-francisco/2024-09-04/data
  - name: boston
    base_url: http://data.insideairbnb.com/united-states/ma/boston/2024-09-13/data
